export const parkingDataArray = [
  {
    id: 1,
    areaName: "South Parking",
    location: "South Side",
    noOfSlots: 3,
    hotel: {
      id: 2,
      name: "Corporate Hotel",
      city: null,
      state: null,
      isActive: null,
      createdAt: null,
      createdBy: null,
      address: null,
      noOfFloors: null,
      floorRoomMapData: null,
      company: null,
      createdByUser: null,
      logoUrl: null,
      email: null,
      contactNo: null,
      contactNos: null,
    },
    isActive: true,
    parkingSlotDataForBick: [
      {
        id: 1,
        slotNumber: "1",
        isOccupied: true,
        parkingVehicleData: {
          id: 2,
          vehicleNo: "OD02R5324",
          vehicleType: "Bick",
          checkInDate: "2024-12-02T11:35:30.000+00:00",
          checkOutDate: null,
        },
        vehicleType: "Bick",
      },
    ],
    parkingSlotDataForCar: [
      {
        id: 2,
        slotNumber: "2",
        isOccupied: false,
        parkingVehicleData: null,
        vehicleType: "Car",
      },
      {
        id: 3,
        slotNumber: "3",
        isOccupied: false,
        parkingVehicleData: null,
        vehicleType: "Car",
      },
    ],
    noOfAvailableSlots: 2,
    noOfOccupiedSlots: 1,
  },
];
